{
 "title": "IoT Dashboard",
 "description": "Cloud native IoT data visualisation pipeline.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Hour Switch Data - All Boxes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id \r\nFROM \"sensor_readings\" \r\nWHERE time >= now() - interval '1 hour'\r\nAND sensor_type = 'switch'"
    }
   ]
  },
  {
   "title": "Last Hour Distance Data - All Boxes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id\r\nFROM \"sensor_readings\"\r\nWHERE time >= now() - interval '1 hour'\r\nAND sensor_type = 'distance'"
    }
   ]
  },
  {
   "title": "24h Switch Data - Box1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id \r\nFROM \"sensor_readings\" \r\nWHERE time >= now() - interval '24 hours'\r\nAND sensor_type = 'switch'\r\nAND device_id = 'iot_box1'"
    }
   ]
  },
  {
   "title": "24h Distance Data - Box1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id \r\nFROM \"sensor_readings\" \r\nWHERE time >= now() - interval '24 hours'\r\nAND sensor_type = 'distance'\r\nAND device_id = 'iot_box1'"
    }
   ]
  },
  {
   "title": "24h Switch Data - Box2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id \r\nFROM \"sensor_readings\" \r\nWHERE time >= now() - interval '24 hours'\r\nAND sensor_type = 'switch'\r\nAND device_id = 'iot_box2'"
    }
   ]
  },
  {
   "title": "24h Distance Data - Box2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value, device_id \r\nFROM \"sensor_readings\" \r\nWHERE time >= now() - interval '24 hours'\r\nAND sensor_type = 'distance'\r\nAND device_id = 'iot_box2'"
    }
   ]
  }
 ]
}